Repository openoereb/pyramid_oereb, pull requests merged in 2018-08, with the labels that each got.

#588 Document new version
  CHANGES.rst
  doc/source/changes.rst
  doc/source/conf.py
  doc/source/contrib/contributing.rst
  doc/source/contrib/print_proxy.rst.mako
  doc/source/standard/sources.rst.mako
  pyramid_oereb/contrib/templates/plr_oereb.py.mako
  pyramid_oereb/lib/records/plr.py
  pyramid_oereb/lib/renderer/__init__.py
  pyramid_oereb/standard/models/airports_building_lines.py
  pyramid_oereb/standard/models/airports_project_planning_zones.py
  pyramid_oereb/standard/models/airports_security_zone_plans.py
  pyramid_oereb/standard/models/contaminated_civil_aviation_sites.py
  pyramid_oereb/standard/models/contaminated_military_sites.py
  pyramid_oereb/standard/models/contaminated_public_transport_sites.py
  pyramid_oereb/standard/models/contaminated_sites.py
  pyramid_oereb/standard/models/forest_distance_lines.py
  pyramid_oereb/standard/models/forest_perimeters.py
  pyramid_oereb/standard/models/groundwater_protection_sites.py
  pyramid_oereb/standard/models/groundwater_protection_zones.py
  pyramid_oereb/standard/models/land_use_plans.py
  pyramid_oereb/standard/models/motorways_building_lines.py
  pyramid_oereb/standard/models/motorways_project_planing_zones.py
  pyramid_oereb/standard/models/noise_sensitivity_levels.py
  pyramid_oereb/standard/models/railways_building_lines.py
  pyramid_oereb/standard/models/railways_project_planning_zones.py
  pyramid_oereb/standard/templates/plr_integer_primary_keys.py.mako
  pyramid_oereb/standard/templates/plr_string_primary_keys.py.mako
Labels: documentation

#593 Fix xml rendering
  pyramid_oereb/lib/renderer/extract/templates/xml/document.xml
  pyramid_oereb/lib/renderer/extract/templates/xml/public_law_restriction.xml
  pyramid_oereb/lib/renderer/extract/templates/xml/view_service.xml
  pyramid_oereb/lib/renderer/extract/xml_.py
  tests/renderer/test_xml.py
Labels: DataExtract XML, bug

#617 Fix JSON for min_NS03, max_NS03, min_NS95 and max_NS95
  pyramid_oereb/lib/renderer/extract/json_.py
Labels: bug

#619 [doc] add infos for database changes
  doc/source/changes.rst
Labels: documentation

#618 [doc] fix path in doc example (must have / after format)
  doc/source/contrib/contributing.rst
Labels: documentation

#622 Fix view service properties in JSON extract
  pyramid_oereb/contrib/print_proxy/mapfish_print.py
  pyramid_oereb/lib/renderer/extract/json_.py
  tests/contrib/print_proxy/resources/expected_getspec_extract.json
  tests/contrib/print_proxy/resources/test_extract.json
  tests/renderer/test_json.py
Labels: bug
